### ISSUE TITLE
white text on white background

### ISSUE THREAD

**Issue by melmelissa** [DmitriK/darkContrast#34] opened 2017-12-12 19:30 UTC
Hello

on the Debian website for package search
https://packages.debian.org/fr/
the boxes are yellow with a white or gray writing according to the dark themes used.
cf my screenshot
https://www.pixenli.com/image/7RaJ8UbB

the problem is present on Firefox 57, Firefox 58 Beta, and Firefox 59 Nightly.
on Debian Cinnamon as well as on Archlinux Cinnamon.
Dark themes tested and problematic:
- Adapta-Nokto
- Ambers
- Adwaita Dark
- arc Dark 
- arc Vaganza 
- Materia Dark
- Material Ubuntu Dark
- Osx Arc Shadow
- United Dark

thank you for your work.
and sorry for my bad English, I'm French.
Melissa.

**Comment by DmitriK** [comment] 2017-12-12 22:09
The issue is that the input elements only change color on focus, which the extension currently does not fix. This is an example of issue #5. Closing this one as a duplicate.

**Closed as completed by DmitriK** 2017-12-12 22:09 UTC
