### ISSUE TITLE
issue with allmusic

### ISSUE THREAD

**Issue by arigit** [DmitriK/darkContrast#22] opened 2017-07-10 04:38 UTC
Using the latest stable in AMO, on firefox 54
There is a small issue with in www.allmusic.com
Opening the page there is a search box in the top right corner. The background is dark grey (nearly black) and the text (when typing there) is black.

**Comment by DmitriK** [comment] 2017-07-12 03:21
I cannot reproduce this. Inspecting the element in dev tools shows the search box is explicitly set to have a white foreground, from the site's own global.css file. The extension correctly detects this as good contrast and does nothing to the element.

I think something else may be interfering on your system. In particular, if you have fought the input contrast issue before, you may have some wayward Stylish sheets or a UserStyles.css file in the config directory that are messing things up a bit.
One thing you can try is go to the extension settings, and add a delay to the extension. If some other addon is changing CSS, the delay gives my extension time to let things settle before attempting to fix elements.

**Comment by arigit** [comment] 2017-07-12 04:25
I did some tests. I did have stylish and disabled it, no dice. I was using Firefox's new embedded "Compact Dark" theme, and I changed it to Default theme, no dice. I checked Firefox > Preferences > Content > Color, and confirmed I wasn't overriding any option, nor "using system colors" &c.

I tried logging out of allmusic to see if that changed the style, no dice, same thing. I tried Allmusic on GNOME's Web (epiphany), the search box indeed came up with a white foreground but Firefox continued to present a black foreground.

Lastly, I disabled "Text Contrast for Dark Themes", and immediately in the check box got fixed, white foregraound on dark background was left intact. Re-enabling the addon again, black foreground again, it's a bit weird.

In Firefox > Addons I can see I have version 1.4.0. I tried re-installing the addon, no dice. If I disable it, then the searchbox gets fixed, it is consistent.

This is on Fedora 25, Gnome / Wayland,  Adwaita-dark

Are you testing with 1.4.0? The beta in AMO seems older that 1.4.0 final.

**Comment by DmitriK** [comment] 2017-07-12 04:50
Ok, can reproduce now. It's something specific about Adwaita-Dark. I normally use a variant of Arc-dark on my systems, which doesn't seem to exhibit this. I can confirm that the google docs issue is also reproducible with adwaita-dark. Will look into this.

For reference, 1.4.0 is the latest released version, so you're good there.

**Comment by arigit** [comment] 2017-07-13 03:59
I tested 1.4.1Beta just posted. It fixed the allmusic problem, that was fast :) - thanks!!

I also rested google docs, the google doc issue  is still there with 1.4.1 though

**Comment by DmitriK** [comment] 2017-07-13 15:08
Excellent, closing this one then.

Fixed in 2dff9dc7a8e75c46d9444065fa6d536eb1dbac7c

**Closed as completed by DmitriK** 2017-07-13 15:08 UTC
