### ISSUE TITLE
Ignored Input on addons.mozilla.org

### ISSUE THREAD

**Issue by ibrokemypie** [DmitriK/darkContrast#25] opened 2017-08-28 06:12 UTC
![image](https://user-images.githubusercontent.com/7827846/29761218-8ff0b4ea-8c0b-11e7-9494-ee03854d7d72.png)
Shown is with text deslected, with text selected however, reading is impossible. Could not screenshot that though.

**Comment by DmitriK** [comment] 2017-08-31 21:54
Duplicate of #11. See [comment](https://github.com/DmitriK/darkContrast/issues/11#issuecomment-271411848). Long story short, Firefox itself prevents all content-script addons from running on AMO, for security reasons.

**Closed as completed by DmitriK** 2017-08-31 21:54 UTC
